# Default values for cluster-observability.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
coo:
    name: cluster-observability-operator
    namespace: openshift-cluster-observability-operator
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

# Labels
# coo<bool>: If not set Cluster Observability Operator will not be managed
# coo-channel<String>: default stable
# coo-install-plan-approval<String>: default Automatic
# coo-source<String>: default redhat-operators
# coo-source-namespace<String>: default openshift-marketplace