# Populate list with:
# oc get complianceremediations -A -o custom-columns=:.metadata.name --no-headers
# Removed from ocp4-stig
# ocp4-stig-project-config-and-template-network-policy
# ocp4-stig-project-config-and-template-network-policy-1
# ocp4-stig-project-config-and-template-resource-quota
# ocp4-stig-project-config-and-template-resource-quota-1
kind: ConfigMap
apiVersion: v1
metadata:
  name: stig-remediation
  namespace: {{ .Values.policy_namespace }}
data:
  ocp4-stig: |
    ocp4-stig-api-server-encryption-provider-cipher
    ocp4-stig-audit-profile-set
    ocp4-stig-oauth-or-oauthclient-inactivity-timeout
    ocp4-stig-oauth-or-oauthclient-token-maxage
  rhcos4-stig: |
    rhcos4-stig-master-audit-access-failed
    rhcos4-stig-master-audit-create-failed
    rhcos4-stig-master-audit-delete-failed
    rhcos4-stig-master-audit-immutable-login-uids
    rhcos4-stig-master-audit-modify-failed
    rhcos4-stig-master-audit-rules-dac-modification-chmod
    rhcos4-stig-master-audit-rules-dac-modification-chown
    rhcos4-stig-master-audit-rules-dac-modification-fchmod
    rhcos4-stig-master-audit-rules-dac-modification-fchmodat
    rhcos4-stig-master-audit-rules-dac-modification-fchown
    rhcos4-stig-master-audit-rules-dac-modification-fchownat
    rhcos4-stig-master-audit-rules-dac-modification-fremovexattr
    rhcos4-stig-master-audit-rules-dac-modification-fsetxattr
    rhcos4-stig-master-audit-rules-dac-modification-lchown
    rhcos4-stig-master-audit-rules-dac-modification-lremovexattr
    rhcos4-stig-master-audit-rules-dac-modification-lsetxattr
    rhcos4-stig-master-audit-rules-dac-modification-removexattr
    rhcos4-stig-master-audit-rules-dac-modification-setxattr
    rhcos4-stig-master-audit-rules-dac-modification-umount
    rhcos4-stig-master-audit-rules-dac-modification-umount2
    rhcos4-stig-master-audit-rules-execution-chcon
    rhcos4-stig-master-audit-rules-execution-semanage
    rhcos4-stig-master-audit-rules-execution-setfiles
    rhcos4-stig-master-audit-rules-execution-setsebool
    rhcos4-stig-master-audit-rules-file-deletion-events-rename
    rhcos4-stig-master-audit-rules-file-deletion-events-renameat
    rhcos4-stig-master-audit-rules-file-deletion-events-rmdir
    rhcos4-stig-master-audit-rules-file-deletion-events-unlink
    rhcos4-stig-master-audit-rules-file-deletion-events-unlinkat
    rhcos4-stig-master-audit-rules-immutable
    rhcos4-stig-master-audit-rules-kernel-module-loading-delete
    rhcos4-stig-master-audit-rules-kernel-module-loading-finit
    rhcos4-stig-master-audit-rules-kernel-module-loading-init
    rhcos4-stig-master-audit-rules-login-events-faillock
    rhcos4-stig-master-audit-rules-login-events-lastlog
    rhcos4-stig-master-audit-rules-login-events-tallylog
    rhcos4-stig-master-audit-rules-media-export
    rhcos4-stig-master-audit-rules-privileged-commands-chage
    rhcos4-stig-master-audit-rules-privileged-commands-chsh
    rhcos4-stig-master-audit-rules-privileged-commands-crontab
    rhcos4-stig-master-audit-rules-privileged-commands-dbus-daemon-launch-helper
    rhcos4-stig-master-audit-rules-privileged-commands-fusermount
    rhcos4-stig-master-audit-rules-privileged-commands-fusermount3
    rhcos4-stig-master-audit-rules-privileged-commands-gpasswd
    rhcos4-stig-master-audit-rules-privileged-commands-grub2-set-bootflag
    rhcos4-stig-master-audit-rules-privileged-commands-mount
    rhcos4-stig-master-audit-rules-privileged-commands-mount-nfs
    rhcos4-stig-master-audit-rules-privileged-commands-newgrp
    rhcos4-stig-master-audit-rules-privileged-commands-pam-timestamp-check
    rhcos4-stig-master-audit-rules-privileged-commands-passwd
    rhcos4-stig-master-audit-rules-privileged-commands-pkexec
    rhcos4-stig-master-audit-rules-privileged-commands-polkit-helper
    rhcos4-stig-master-audit-rules-privileged-commands-postdrop
    rhcos4-stig-master-audit-rules-privileged-commands-postqueue
    rhcos4-stig-master-audit-rules-privileged-commands-pt-chown
    rhcos4-stig-master-audit-rules-privileged-commands-ssh-keysign
    rhcos4-stig-master-audit-rules-privileged-commands-sssd-krb5-child
    rhcos4-stig-master-audit-rules-privileged-commands-sssd-ldap-child
    rhcos4-stig-master-audit-rules-privileged-commands-sssd-proxy-child
    rhcos4-stig-master-audit-rules-privileged-commands-sssd-selinux-child
    rhcos4-stig-master-audit-rules-privileged-commands-su
    rhcos4-stig-master-audit-rules-privileged-commands-sudo
    rhcos4-stig-master-audit-rules-privileged-commands-sudoedit
    rhcos4-stig-master-audit-rules-privileged-commands-umount
    rhcos4-stig-master-audit-rules-privileged-commands-unix-chkpwd
    rhcos4-stig-master-audit-rules-privileged-commands-userhelper
    rhcos4-stig-master-audit-rules-privileged-commands-utempter
    rhcos4-stig-master-audit-rules-privileged-commands-write
    rhcos4-stig-master-audit-rules-session-events
    rhcos4-stig-master-audit-rules-sysadmin-actions
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-creat
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-ftruncate
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-open
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-open-by-handle-at
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-openat
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-rename
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-renameat
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-truncate
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-unlink
    rhcos4-stig-master-audit-rules-unsuccessful-file-modification-unlinkat
    rhcos4-stig-master-audit-rules-usergroup-modification
    rhcos4-stig-master-audit-rules-usergroup-modification-group
    rhcos4-stig-master-audit-rules-usergroup-modification-gshadow
    rhcos4-stig-master-audit-rules-usergroup-modification-opasswd
    rhcos4-stig-master-audit-rules-usergroup-modification-passwd
    rhcos4-stig-master-audit-rules-usergroup-modification-shadow
    rhcos4-stig-master-auditd-data-disk-error-action
    rhcos4-stig-master-configure-usbguard-auditbackend
    rhcos4-stig-master-coreos-audit-backlog-limit-kernel-argument
    rhcos4-stig-master-coreos-audit-option
    rhcos4-stig-master-coreos-page-poison-kernel-argument
    rhcos4-stig-master-coreos-slub-debug-kernel-argument
    rhcos4-stig-master-coreos-vsyscall-kernel-argument
    rhcos4-stig-master-kernel-module-usb-storage-disabled
    rhcos4-stig-master-package-usbguard-installed
    rhcos4-stig-master-service-sshd-disabled
    rhcos4-stig-master-service-usbguard-enabled
    rhcos4-stig-master-sshd-disable-root-login
    rhcos4-stig-master-sysctl-kernel-dmesg-restrict
    rhcos4-stig-master-sysctl-kernel-perf-event-paranoid
    rhcos4-stig-master-sysctl-kernel-randomize-va-space
    rhcos4-stig-master-usbguard-allow-hid-and-hub
    rhcos4-stig-worker-audit-access-failed
    rhcos4-stig-worker-audit-create-failed
    rhcos4-stig-worker-audit-delete-failed
    rhcos4-stig-worker-audit-immutable-login-uids
    rhcos4-stig-worker-audit-modify-failed
    rhcos4-stig-worker-audit-rules-dac-modification-chmod
    rhcos4-stig-worker-audit-rules-dac-modification-chown
    rhcos4-stig-worker-audit-rules-dac-modification-fchmod
    rhcos4-stig-worker-audit-rules-dac-modification-fchmodat
    rhcos4-stig-worker-audit-rules-dac-modification-fchown
    rhcos4-stig-worker-audit-rules-dac-modification-fchownat
    rhcos4-stig-worker-audit-rules-dac-modification-fremovexattr
    rhcos4-stig-worker-audit-rules-dac-modification-fsetxattr
    rhcos4-stig-worker-audit-rules-dac-modification-lchown
    rhcos4-stig-worker-audit-rules-dac-modification-lremovexattr
    rhcos4-stig-worker-audit-rules-dac-modification-lsetxattr
    rhcos4-stig-worker-audit-rules-dac-modification-removexattr
    rhcos4-stig-worker-audit-rules-dac-modification-setxattr
    rhcos4-stig-worker-audit-rules-dac-modification-umount
    rhcos4-stig-worker-audit-rules-dac-modification-umount2
    rhcos4-stig-worker-audit-rules-execution-chcon
    rhcos4-stig-worker-audit-rules-execution-semanage
    rhcos4-stig-worker-audit-rules-execution-setfiles
    rhcos4-stig-worker-audit-rules-execution-setsebool
    rhcos4-stig-worker-audit-rules-file-deletion-events-rename
    rhcos4-stig-worker-audit-rules-file-deletion-events-renameat
    rhcos4-stig-worker-audit-rules-file-deletion-events-rmdir
    rhcos4-stig-worker-audit-rules-file-deletion-events-unlink
    rhcos4-stig-worker-audit-rules-file-deletion-events-unlinkat
    rhcos4-stig-worker-audit-rules-immutable
    rhcos4-stig-worker-audit-rules-kernel-module-loading-delete
    rhcos4-stig-worker-audit-rules-kernel-module-loading-finit
    rhcos4-stig-worker-audit-rules-kernel-module-loading-init
    rhcos4-stig-worker-audit-rules-login-events-faillock
    rhcos4-stig-worker-audit-rules-login-events-lastlog
    rhcos4-stig-worker-audit-rules-login-events-tallylog
    rhcos4-stig-worker-audit-rules-media-export
    rhcos4-stig-worker-audit-rules-privileged-commands-chage
    rhcos4-stig-worker-audit-rules-privileged-commands-chsh
    rhcos4-stig-worker-audit-rules-privileged-commands-crontab
    rhcos4-stig-worker-audit-rules-privileged-commands-dbus-daemon-launch-helper
    rhcos4-stig-worker-audit-rules-privileged-commands-fusermount
    rhcos4-stig-worker-audit-rules-privileged-commands-fusermount3
    rhcos4-stig-worker-audit-rules-privileged-commands-gpasswd
    rhcos4-stig-worker-audit-rules-privileged-commands-grub2-set-bootflag
    rhcos4-stig-worker-audit-rules-privileged-commands-mount
    rhcos4-stig-worker-audit-rules-privileged-commands-mount-nfs
    rhcos4-stig-worker-audit-rules-privileged-commands-newgrp
    rhcos4-stig-worker-audit-rules-privileged-commands-pam-timestamp-check
    rhcos4-stig-worker-audit-rules-privileged-commands-passwd
    rhcos4-stig-worker-audit-rules-privileged-commands-pkexec
    rhcos4-stig-worker-audit-rules-privileged-commands-polkit-helper
    rhcos4-stig-worker-audit-rules-privileged-commands-postdrop
    rhcos4-stig-worker-audit-rules-privileged-commands-postqueue
    rhcos4-stig-worker-audit-rules-privileged-commands-pt-chown
    rhcos4-stig-worker-audit-rules-privileged-commands-ssh-keysign
    rhcos4-stig-worker-audit-rules-privileged-commands-sssd-krb5-child
    rhcos4-stig-worker-audit-rules-privileged-commands-sssd-ldap-child
    rhcos4-stig-worker-audit-rules-privileged-commands-sssd-proxy-child
    rhcos4-stig-worker-audit-rules-privileged-commands-sssd-selinux-child
    rhcos4-stig-worker-audit-rules-privileged-commands-su
    rhcos4-stig-worker-audit-rules-privileged-commands-sudo
    rhcos4-stig-worker-audit-rules-privileged-commands-sudoedit
    rhcos4-stig-worker-audit-rules-privileged-commands-umount
    rhcos4-stig-worker-audit-rules-privileged-commands-unix-chkpwd
    rhcos4-stig-worker-audit-rules-privileged-commands-userhelper
    rhcos4-stig-worker-audit-rules-privileged-commands-utempter
    rhcos4-stig-worker-audit-rules-privileged-commands-write
    rhcos4-stig-worker-audit-rules-session-events
    rhcos4-stig-worker-audit-rules-sysadmin-actions
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-creat
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-ftruncate
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-open
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-open-by-handle-at
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-openat
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-rename
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-renameat
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-truncate
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-unlink
    rhcos4-stig-worker-audit-rules-unsuccessful-file-modification-unlinkat
    rhcos4-stig-worker-audit-rules-usergroup-modification
    rhcos4-stig-worker-audit-rules-usergroup-modification-group
    rhcos4-stig-worker-audit-rules-usergroup-modification-gshadow
    rhcos4-stig-worker-audit-rules-usergroup-modification-opasswd
    rhcos4-stig-worker-audit-rules-usergroup-modification-passwd
    rhcos4-stig-worker-audit-rules-usergroup-modification-shadow
    rhcos4-stig-worker-auditd-data-disk-error-action
    rhcos4-stig-worker-configure-usbguard-auditbackend
    rhcos4-stig-worker-coreos-audit-backlog-limit-kernel-argument
    rhcos4-stig-worker-coreos-audit-option
    rhcos4-stig-worker-coreos-page-poison-kernel-argument
    rhcos4-stig-worker-coreos-slub-debug-kernel-argument
    rhcos4-stig-worker-coreos-vsyscall-kernel-argument
    rhcos4-stig-worker-kernel-module-usb-storage-disabled
    rhcos4-stig-worker-package-usbguard-installed
    rhcos4-stig-worker-service-sshd-disabled
    rhcos4-stig-worker-service-usbguard-enabled
    rhcos4-stig-worker-sshd-disable-root-login
    rhcos4-stig-worker-sysctl-kernel-dmesg-restrict
    rhcos4-stig-worker-sysctl-kernel-perf-event-paranoid
    rhcos4-stig-worker-sysctl-kernel-randomize-va-space
    rhcos4-stig-worker-usbguard-allow-hid-and-hub