# Default values for rh-acm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
acm: 
  subName: advanced-cluster-management
  namespace: open-cluster-management
  channel: release-2.10
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  installPlanApproval: Automatic
  name: advanced-cluster-management
  disable_hub_self_management: false
  enable_backup: false
  policy_namespace: open-cluster-policies
  gitops_namespace: openshift-gitops
  gitops_auto_clusterset: managed
  clusterSets:
    - hub
    - managed
