# Default values for storage-nodes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
storageNodes:
  clusterSets:
    - hub
    - managed
  zones:
    - us-east-2c
# Defaults to worker node instance type for first machine set if finds
# instanceType: i4i.8xlarge