# Default values for rh-acm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
acm: 
  namespace: open-cluster-management
  channel: release-2.13
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  installPlanApproval: Automatic
  name: advanced-cluster-management
  disable_hub_self_management: false
  availabilityConfig: High
  enable_backup: false
  gitops_namespace: openshift-gitops
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   sandbox:
#     labels:
#       test3: 'test'
#   managed:
#     labels:
#       test4: 'test'